//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AccountList
    {
       
        public AccountList()
        {
            this.AccountTransactions = new HashSet<AccountTransaction>();
        }
    
        public int Account_Number { get; set; }
        public string Account_Name { get; set; }
        public string Account_Type { get; set; }
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime Balance_Date { get; set; }
        public string Currency { get; set; }
        public decimal Opening_Balance { get; set; }
    
      
        public virtual ICollection<AccountTransaction> AccountTransactions { get; set; }
    }
}
