//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTransaction
    {
        public int Account_Number { get; set; }
        public string Account_Name { get; set; }
        public System.DateTime Value_Date { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Debit_Amount { get; set; }
        public Nullable<decimal> Credit_Amount { get; set; }
        public string Debit_Credit { get; set; }
        public string TransactionNarrative { get; set; }
    
        public virtual AccountList AccountList { get; set; }
    }
}
